### PR TITLE
Add no-top-level-arrow

### PR DESCRIPTION
**Pull request by DamienCassou**
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/ftgp-eslint/78)

### CODE REVIEW

**Review by JohanBriglia — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/ftgp-eslint/78#-:-NOtJGiU9vzH-fFXGUNG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BenjaminVanRyseghem and @JanLayola)

**Review by BenjaminVanRyseghem — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/ftgp-eslint/78)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @DamienCassou, @JanLayola, and @JohanBriglia)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/ftgp-eslint/78#-NOtRUgvEvg_3lqO55I2:-NOtRUgvEvg_3lqO55I3:ba1gnvo) (no related file):*
Did I miss a discussion? Where does this come from? And why?

___

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/ftgp-eslint/78)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem, @JanLayola, and @JohanBriglia)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/ftgp-eslint/78#-NOtRUgvEvg_3lqO55I2:-NOtSkKq9JQjauyGKUTw:btkoqqa) (no related file):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

Did I miss a discussion? Where does this come from? And why?
</blockquote></details>

We discussed it a bit together a few days ago but there hasn't been any formal discussion with others. We currently have 2 ways to define top-level functions and I'm always trying to make the code as coherent as possible. This rule will help us doing just that: coherence.

___

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/ftgp-eslint/78)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem, @JanLayola, and @JohanBriglia)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/ftgp-eslint/78#-NOtRUgvEvg_3lqO55I2:-NOxRPD72pCm6Qbo3t8L:ba3gg7p) (no related file):*
<details><summary><i>Previously, DamienCassou (Damien Cassou) wrote…</i></summary><blockquote>

We discussed it a bit together a few days ago but there hasn't been any formal discussion with others. We currently have 2 ways to define top-level functions and I'm always trying to make the code as coherent as possible. This rule will help us doing just that: coherence.
</blockquote></details>

I started the discussion in https://3.basecamp.com/4201305/buckets/11549816/messages/5869881824

___

**Pull request closed without merging**
